# Libellés et descriptions : voir translations/*.json.
import_csv:
  fields:
    path:
      required: false
      example: /config/es_strasbourg/Consommation_Journaliere.csv
      selector:
        text:

clear_statistics:
